### ISSUE TITLE
Properties with names colliding with immutable methods (e.g. update, merge) are getting lost

### ISSUE THREAD

**Issue by lzrski** [rtfeldman/seamless-immutable#130]
Consider this object:

```javascript
{ links:
   { update: 'http://api.dev/...',
     delete: 'http://api.dev/...' } }
```

If one pass it to `seamless-immutable`, this will be returned:

```javascript
{ links:
   { delete: 'http://api.dev/...' } }
```

**Comment by lzrski** [comment]
Maybe it's a good reason to revisit #81?

**Comment by lzrski** [comment]
Given prior discussion at #131 it seems like correct solution to this problem is to add Immutable specific methods to the constructor (aka making them static). This was previously proposed in #81 .

---

Do you think that methods should be defined only on the constructor, or also on instances?

The constructor only approach seems more elegant, but would be a serious breaking change.

With constructor + instance approach, we still have to figure out how collisions with original object properties should be resolved. Also things like that:

```javascript
immutable_instance.merge({ without: "data" })
```

**Comment by mariusk** [comment]
I'm late to the party, but I just migrated a code base from immutable.js to this and was immediately hit by one member deep in a object hierarchy named `set`.  On the one hand, migration was easy as some of the common API members have identical names and signatures as immutable.js (`setIn`), but unless anybody else have better ideas I would suggest some unlikely prefix or postfix for all method names or similar (e.g. `setInImm`, `imSetIn` or something like that).

**Comment by suchipi** [comment]
Ran into this same issue today (with `update`). It'd be nice if we could do:
```js
import Immutable, { merge } from "seamless-immutable";

let options = Immutable({ merge: "true" });
options = merge(options, { something: "else" });
console.log(options); // { merge: true, something: "else" }
```

**Comment by saivann** [comment]
I have just submitted #158 to add static methods support in the `Immutable` constructor.

```
var obj = Immutable.from({});
Immutable.setIn(obj, ['key'], value);
```

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/seamless-immutable/pull/158

**Comment by suchipi** [comment]
Does #158 actually fix it? Just adding static methods won't prevent name collision from the instance methods that are also still present. The collision won't be truly fixed until the instance names are also removed; which would be a breaking change (but a welcome one, in my opinion).

**Comment by rtfeldman** [comment]
Gotcha...I think a feature request for "avoid clobbering existing fields" makes sense.

Want to open one? 😄

**Comment by saivann** [comment]
Right so at least now there is a way to avoid this bug using the new syntax. Disabling the old instance syntax is pretty simple but indeed not a small breaking change.

Perhaps as a first step the documentation can be updated to stop promoting the old syntax? We can also easily insert a "deprecated" warning in the browser javascript console when users continue using the existing instance syntax for a while and eventually disable that syntax?

**Comment by saivann** [comment]
Oh I see. I got this wrong, it is the custom properties that are getting lost, not the seamless-immutable instance methods. To allow overriding those properties, I guess we could set `writable` to `true` here. This would replace current bug by another, and make new static methods fully working against this case.

```
    Object.defineProperty(target, methodName, {
      enumerable: false,
      configurable: false,
      writable: true,
      value: value
    });
```

**Comment by saivann** [comment]
Oh I see. I got this wrong, it is the custom properties that are getting lost, not the seamless-immutable instance methods. To allow overriding those, I guess we could set `writable` to `true` here. This would replace current bug by another, and make new static methods fully working against all cases.

```
    Object.defineProperty(target, methodName, {
      enumerable: false,
      configurable: false,
      writable: true,
      value: value
    });
```

I am happy to submit this, documentation update, test units, and deprecation warning, if @rtfeldman thinks this is a good approach to this problem.

**Comment by saivann** [comment]
PR to finalize this fix
https://github.com/rtfeldman/seamless-immutable/pull/160
