### ISSUE TITLE
Fix tests that relied on Lodash 4

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/seamless-immutable#179]
I mistakenly upgraded our tests to use Lodash 4, not realizing some of the features in Lodash 4 did not work in IE9-10. (`seamless-immutable` itself does not depend on Lodash; this was for tests only.)

We subsequently added tests that relied on those features, causing IE9-10 tests to fail. I have reverted to Lodash 3.10 and disabled those tests, so that the other tests can complete cross-browser testing as normal. However, now we have a few pending tests that need to be rewritten to use Lodash 3.10 features instead of the Lodash 4 features they currently use.

The pending tests are marked with `xit` in the test suite.

Help on this would be greatly appreciated! ❤️

**Comment by saivann** [comment]
I am not very familiar with the infrastructure here, any easy way to reproduce the issue?

I tried to open a pull request and let it run against travis, expecting that I would get relevant output from there (assuming travis had credentials to run cross-browser tests with some third party service). However I am always getting only:

```
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.
```

This is by contrast to https://github.com/rtfeldman/seamless-immutable/pull/178 where there is one travis instance that reported tests that passed, with explicit mentions of different browsers. I am not sure how to get those tests to run while not being rtfeldman :) .

**Comment by rtfeldman** [comment]
@saivann I pushed what theoretically seems like a fix for that credentials complaint.

That said, if you can get all the tests passing locally on Lodash 3.10, that should be good enough. 🙂

**Comment by ryantemple** [comment]
I'm still seeing the same error as above - the only test that seems to break locally is the omitBy test here https://github.com/rtfeldman/seamless-immutable/blob/master/test/ImmutableObject/test-without.js#L176 which I've raised a PR for #196

**Comment by wmertens** [comment]
Hmm, lodash only dropped support for ie8 and below. So either you found a
bug in lodash or you need to load the es5 shim?
