### ISSUE TITLE
Merge returns a new object even when there is no change

### ISSUE THREAD

**Issue by tusharmath** [rtfeldman/seamless-immutable#70]
```javascript
var immutable = require('seamless-immutable')
var c = immutable({a: {b: 1}})
console.log(c.merge({a: {b: 1}}, {deep: true}) === c) //returns false
```

The output should return `true` but returns false instead.

**Comment by rtfeldman** [comment]
Thanks for bringing this up!

Unfortunately, there would be a significant performance cost to enabling this; `merge` would have to keep track of whether any modifications had been made, and inspect every current value before merging along the way.

I don't think the performance overhead is worth making this work.

**Comment by tusharmath** [comment]
This is a little wierd because u see —

```javascript 

var obj = Immutable({
  a: {aa: 1},
  b: {bb: 2}
})
var obj2 = obj.merge({b: {bb: 2}}, {deep: true})

console.log(obj.b === obj2.b) // actually returns true
```

So you are doing a check here right? I can get the same behavior by just wrapping the whole object `c` inside another temp object.

**Comment by rtfeldman** [comment]
Hm, sure enough! It looks like we're already doing this and incurring the performance cost, so I guess it's empirically not a performance problem. :laughing: My bad!

 I'll look into this.

**Comment by rtfeldman** [comment]
Fixed and published as 4.0.2. Thanks for reporting this @tusharmath, and sorry I didn't look far enough into it the first time around!

**Comment by tusharmath** [comment]
@rtfeldman No need for sorry. Thanks a ton for fixing it so quickly.

**Comment by zuk** [comment]
Looks like this is still happening for objects with nested arrays. For example:

```
var a = Immutable({foo: []})
var b = Immutable({foo: []})
var ab = a.merge(b, {deep: true})
ab === a  // => false
```

Without a nested array it works as expected:

```
var a = Immutable({foo: {}})
var b = Immutable({foo: {}})
var ab = a.merge(b, {deep: true})
ab === a  // => true
```

**Comment by rtfeldman** [comment]
@zuk can you open a separate issue for that?

**Comment by zuk** [comment]
Sure, opened it as #94
